Add Sanity
Royce551/FRESHMusicPlayer-WinForms pull request #4
Opened 2020-07-20 02:31 UTC by vicr123

This PR sprinkles some sanity into the Updates page and also filters for common file types in the Open dialog box.

2020-07-20 02:35 UTC, ntfluoride commented
### lmao

2020-07-20 02:35 UTC, Royce551 commented
i'm dyinggggggg

2020-07-20 02:36 UTC, ntfluoride commented
merge i dare you

2020-07-20 02:39 UTC, Royce551 requested changes

2020-07-20 02:39 UTC, Royce551 commented on FRESHMusicPlayer/FRESHMusicPlayer/UserInterface.cs
> +                selectFileDialog.Filter = "Audio|*.mp3;*.wma;*.oga;*.ogg;*.acc;*.wav;*.flec|All Files|*";
does not show all file formats naudio supports, also "flac" is mispelled

2020-07-20 02:42 UTC, ntfluoride commented on FRESHMusicPlayer/FRESHMusicPlayer/UserInterface.cs
> +                selectFileDialog.Filter = "Audio|*.mp3;*.wma;*.oga;*.ogg;*.acc;*.wav;*.flec|All Files|*";
Dear Sir and/or Madam,

I believe you have too high of standards for this piece of software. Mr. Victor Tran is a very competent developer who never makes mistakes. He is six feet tall and owns five mansions.

2020-07-22 19:35 UTC, Royce551 commented
See #5

2020-07-22 19:35 UTC, closed without merging